services:
  event-manager-frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 4173:4173
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
    env_file:
      - .env

networks:
  frontend-network:
    driver: bridge
  backend-network:
    internal: true